### ISSUE TITLE
"Flattened" router metrics? /item/123 => /item/:id

### ISSUE THREAD

**Issue by apinstein** [angulartics/angulartics#116]
Currently any route set up like /item/:id will end up being logged to _each_ page. While this is great when you care about the difference between ID's, it's the opposite of what you want when trying to see aggregate statistics.

What do you think of the idea that an option is added to make angulartics flatten these routes before reporting?

I can think of several approaches:
1. A callback that lets the app munge the URL that will be reported before it is sent to the analytics backend.
1. Some kind of per-route boolean "flattenUrls"
1. Other ideas?

**Comment by brunomperes** [comment]
Thanks @apinstein for the snippets

Another solution would be to submit the `toState.url`, instead of regenerating the it with `$state.href()` after changing the params values to `:paramName`.

And to anyone refering to this, perhaps it could also be interesting to submit the params to your tracking service as well by using `eventTrack()`:
````javascript
var eventParams = angular.extend(toParams, {page: toState.url});
$analytics.eventTrack('Page Viewed', eventParams);
````

**Comment by tracyalison11** [comment]
I am wondering if there are any additional solutions since this issue was discussed over a year ago? I have the same issue in that URLs constructed in my application contain GUIDs and I need to view them on Google analytics as an aggregated total. Please see a more detailed explanation here: http://stackoverflow.com/questions/32575709/using-angulartics-and-google-analytics-for-dynamic-and-unique-urls

@brunomperes - not sure I quite understand your solution because I am not sure where you are putting this code? Is this something you put in the controller?

Thanks in advance!

**Comment by brunomperes** [comment]
@tracyalison11 I'm using it in the same context as @apinstein, the idea is that you already have the flatten url when you declare the state's url. So to track the url without the params you simply read it from `toState.url`, instead of flattening it back from the `$state.href(toState.name)`. What I do additionally is to track `toParams`, so I can analyze with what parameters my pages are being seen. See the snippet below.

Note: I have an option to disable tracking the `toParams` by declaring the state with `angulartics.trackParams` set to `false` (reset password token in this case).
```javascript
.state('reset-password', {
    url: '/reset-password/:password_token',
    templateUrl: 'modules/user/reset-password.html',
    controller: 'ResetPasswordCtrl',
    angulartics: {
      trackParams: false
    }
})
```
```javascript
.run(['$rootScope', '$analytics', function ($rootScope, $analytics) {

    $rootScope.$on('$stateChangeSuccess', function (event, toState, toParams) {

      var url = toState.url; // '/reset-password/:password_token' for the state above
      var params = {};

      // Decides to track info from toParams, default is to track unless explicitly set to false
      if (!toState.angulartics || toState.angulartics.trackParams !== false){
        params = toParams;
      }

      params = angular.extend(params, {page: url});

      $analytics.eventTrack('Page Viewed', params);
      //You can use pageTrack(url) instead, but it doesn't allow you to track info from toParams
    });
}])
```
In my context `eventTrack('Page Viewed')` makes sense because I use mixpanel, I'm not sure how it works on GA.

**Comment by ProLoser** [comment]
Nothing stops you from sending params in page track. You may need to figure
out what property ga doesn't discard perhaps.
