### ISSUE TITLE
Include GA account as setting

### ISSUE THREAD

**Issue by cmbirk** [angulartics/angulartics#379]
I'm trying to include analytics tracking as optional in another OSS project.

Not every installation will have a GA account, so I would like to include it conditionally.    This isn't possible if I have to include the default GA embed code for every installation.

Is there any interest in including it conditionally so that when instantiating angulartics I provide an account and it injects the GA default code on the page?  I would be willing to help set this up if there is, but may need some guidance.

**Comment by luisfarzati** [comment]
This was one of my first thoughts when started Angulartics. The reason I left this behind is that snippets may change and/or people may use it differently. 

Why not conditionally injecting the code yourself, rather than trying to do it via Angulartics?

**Comment by cmbirk** [comment]
Yeah, that's what I ended up doing.

I assume that GA is one of the biggest, if not *the biggest*, use case here and many people would probably gain from a setup like this.  I do understand if that's not in the cards for this project, though.

**Comment by luisfarzati** [comment]
I hear you. But even in that case, I think a better place to implement this would be in the plugin itself. Either by adding a `angular.run()` or just exposing a method at `config` time to let the user enable this option.

Each plugin could implement this. Perhaps what we can do is to normalize the method name in order to keep it clean and intuitive.

Feel free to submit this issue in the [GA plugin repo](http://github.com/angulartics/angulartics-google-analytics) and, of course, you are welcomed to submit a PR (cc'ing @lunks who wants to take ownership of this plugin).

**Comment by ProLoser** [comment]
I do not believe this is the responsibility of angulartics for the reasons stated by @luisfarzati and it would lead down a path of expectations and inconsistencies imposed on all the other plugins, so I'm closing this issue (unless there are objections from @angulartics/core
