### ISSUE TITLE
Allow trackPage(path) of full page path in Google Analytics

### ISSUE THREAD

**Issue by short4bmoney** [angulartics/angulartics#399]
The **path** variable in the `trackPage(path)` call for Google Analytics is desirable to include query parameters as well as hash in-page anchors.

Where would this customization be configured?

**Comment by luisfarzati** [comment]
This is not supported for now.

**Comment by DanWilkerson** [comment]
@andydapenguin In Google Tag Manager, create a new Variable of the type URL, then select Query from the dropdown. Name it Page Query String. Then adjust your Angulartics pageviews settings so that the value of the **page** Field to Set is:

{{Page Query String}}{{angulartics page path}}

That should do what you want.

**Comment by timelf123** [comment]
If you are using `Segment -> GA` you can check a box to enable this
