### ISSUE TITLE
update version before tagging

### ISSUE THREAD

**Issue by smarts** [angulartics/angulartics#418]
Please don't forget to update the version before tagging. It's confusing to view the content at `https://cdnjs.cloudflare.com/ajax/libs/angulartics/0.20.0/angulartics.min.js` and see `@license Angulartics v0.19.2`

Also, you probably want to update the URL in the source files as well from `http://luisfarzati.github.io/angulartics` to `http://angulartics.github.io`

**Comment by ProLoser** [comment]
Ah did I do that? Sorry about that.

**Comment by earth2marsh** [comment]
:+1: The license in the preamble comments was confusing to me, too. I'm not sure there is reason to stamp the version number into all those files, instead consider indicating the version number once to avoid these kinds of discrepancies. 

Also, rather than putting version info in commit messages, consider tagging releases instead.

**Comment by timelf123** [comment]
I agree it is confusing. It should either be part of the build process or not included at all (bower.json and package.json give versions)

**Comment by smarts** [comment]
:+1: to what @earth2marsh said

**Comment by lunks** [comment]
I agree. I found it confusing when joining the project as well.

**Comment by timelf123** [comment]
Fixed in 0.2.3
