### ISSUE TITLE
Better debug mode

### ISSUE THREAD

**Issue by ChristoRibeiro** [angulartics/angulartics#520]
Hi,

Actually to debug $analytics we have to inject `analytics.debug`. After the debug, we remove it.

I suggest a better way:  
1/ Get a method debugEnabled `$analytics.debugEnabled(true|false)`. With Grunt/Gulp it is more easy to turn on/off the debug with an Env variable `$analytics.debugEnabled(ItsTheDevEnv)`.

2/ Or use the `$log` of AngularJS instead of `console.log()`. I can turn on/off the log easier `$logProvider.debugEnabled(false)`.

In both solutions, I keep my dependencies `angulartics.debug` and log when I need.

What do you think?

**Comment by timelf123** [comment]
https://github.com/angulartics/angulartics/releases/tag/1.3.0

Use `$analytics.setOptOut(boolean Optout);`

**Comment by myspivey** [comment]
It would be nice to have a way to turn off the tracking, but still output the actions to the console. I hate pushing a ton of data to signal just to test that the values I want are being assigned properly. If that is what this is going for I agree. all developerMode does is just kill all tracking which is not useful for debugging.

**Comment by timelf123** [comment]
PR welcome as always

**Comment by myspivey** [comment]
Seems like there might want to be some discussion before someone takes the time to write the PR. developerMode has been around for quite some time and this product has a lot of users so any changes to that could have pretty sweeping impacts. Just glancing at it, seems to be that leaving developerMode as is would be fine, if handlers could be added explicitly for debugging. Rather than just registering extra listeners that do a trace, we separate that out into their own debug handlers. It would involve an extra store for that, but overall I do not imagine it would add much. It would by its nature not care about developerMode. Could be something like 

`$analyticsProvider.registerDebugHandler(function (event) {
    console.log('Page tracking: ', event.path);
    console.log("Event tracking: ", event.action, event.properties);
  });`

The only issue with an approach like that is it does not really fit how the registration of the base handles things as really it just hands off that registration functionality to the plugins while we in this case I would imagine do not want that behavior. Added benefits are that it greatly simplifies and expands how one could debug and where they want that debugging to live and the actions that need to happen when debugging.

**Comment by mikey0000** [comment]
setOptOut results in an error
`this.settings.optOut` is undefined

**Comment by timelf123** [comment]
@mikey0000 
 fixed in https://github.com/angulartics/angulartics/commit/0de030f3a904c961ff047efdcf434610b4656df8
